// <auto-generated>
// Code generated by LUISGen Comision.json -cs Luis.Comision -o .
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class Comision: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            Saludo, 
            Ventas, 
            Compensacion, 
            Reclamaciones, 
            Penalizaciones, 
            Comision, 
            Cancel, 
            None
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {

            // Built-in entities
            public DateTimeSpec[] datetime;

            // Lists
            public string[][] Agente;

            public string[][] ReclamacionMessage;

            public string[][] VentaMessage;

            // Composites
            public class _Instancede
            {
                public InstanceData[] Agente;
            }
            public class deClass
            {
                public string[][] Agente;
                [JsonProperty("$instance")]
                public _Instancede _instance;
            }
            public deClass[] de;

            public class _Instancepara
            {
                public InstanceData[] Agente;
            }
            public class paraClass
            {
                public string[][] Agente;
                [JsonProperty("$instance")]
                public _Instancepara _instance;
            }
            public paraClass[] para;

            // Instance
            public class _Instance
            {
                public InstanceData[] Agente;
                public InstanceData[] ReclamacionMessage;
                public InstanceData[] VentaMessage;
                public InstanceData[] datetime;
                public InstanceData[] de;
                public InstanceData[] para;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<Comision>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
